-
  name: 'Refactory OAuth - Povider Index route'
  uriPattern: ''
  defaults:
    '@package':    'Refactory.OAuth'
    '@controller': 'Provider'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'Refactory OAuth - Controllers route'
  uriPattern: '{@controller}s'
  defaults:
    '@package':    'Refactory.OAuth'
    '@controller': 'App'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'Refactory OAuth - Controller actions route'
  uriPattern: '{@controller}s/{@action}'
  defaults:
    '@package':    'Refactory.OAuth'
    '@controller': 'App'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true
