-
  name: 'CloudTomatoes OAuth2 - Povider Index route'
  uriPattern: 'providers'
  defaults:
    '@package':    'CloudTomatoes.OAuth2'
    '@controller': 'Provider'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'CloudTomatoes OAuth2 - Controllers route'
  uriPattern: '{@controller}s'
  defaults:
    '@package':    'CloudTomatoes.OAuth2'
    '@controller': 'App'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true

-
  name: 'CloudTomatoes OAuth2 - Controller actions route'
  uriPattern: '{@controller}s/{@action}'
  defaults:
    '@package':    'CloudTomatoes.OAuth2'
    '@controller': 'App'
    '@action':     'index'
    '@format':     'html'
  appendExceedingArguments: true
