Neos:
  Flow:
    mvc:
      routes:
        'CloudTomatoes.OAuth2':
          position: 'start'
Flownative:
  OAuth2:
    Client:
      services:
        #GCP
        - name: 'google-cloud-platform'
          className: 'CloudTomatoes\OAuth2\OAuthServices\GCPClient'
CloudTomatoes:
  OAuth2:
    default:
      api:
        version: '2020-06-01'
