Flownative:
  OAuth2:
    Client:
      token:
        # default lifetime of new tokens in seconds, null = never
        defaultLifetime: null
      services:
        #GCP
        - name: 'google-cloud-platform'
          className: 'CloudTomatoes\OAuth2\OAuthServices\GCPClient'
CloudTomatoes:
  OAuth2:
    apiVersion:
      default: '2020-06-01'
      allowed:
        - '2021-01-01'
        - '2020-08-01'
        - '2020-06-01'
        - '2019-07-01'
        - '2019-06-01'
        - '2018-05-01'
